services:
  - type: web
    name: messenger-demo
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          property: connectionString

  - type: postgres
    name: messenger-db
<<<<<<< HEAD
    plan: free
=======
    plan: free
>>>>>>> bfd750f374eabbd1c4cbd33797d162731893fc7f
